name: Security Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build WebGoat (Maven)
        run: mvn clean install -DskipTests

      # SCA (Dependency Check)
      - name: Run OWASP Dependency-Check (SCA)
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'WebGoat'
          path: '.'
          format: 'ALL'

      # SAST (CodeQL)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Build for CodeQL
        run: mvn clean compile -DskipTests

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      # DAST (OWASP ZAP)
      - name: Start WebGoat server
        run: java -jar webgoat-server/target/webgoat-server-*.jar &
      
      - name: Wait for WebGoat to start
        run: |
          for i in {1..30}; do
            nc -zv localhost 8080 && break
            sleep 5
          done

      - name: Run OWASP ZAP Baseline Scan (DAST)
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:8080/WebGoat'
